### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by Drun555** [browningluke/mangathr-legacy#8]
First of all - thank you for your work. This thing is exactly what I need, there's just no other utility to dump MangaDex with ComicsInfo.xml. And "subscribe" ability is very promising. This should be absolutely ideal companion for Komga.

Unfortunately, after installing I get error listed below. I tried to re-install module-alias in the mangathr folder, but had no success. Is there anything else I should try to do?

```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../dist/main'
Require stack:
- /usr/local/lib/node_modules/mangathr/bin/mangathr.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._resolveFilename (/usr/local/lib/node_modules/mangathr/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/mangathr/bin/mangathr.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/mangathr/bin/mangathr.js' ]
}
```

**Comment by browningluke** [comment]
Hey there, thanks for your comment! I'm glad someone finds it useful :). Just for your information, this repo isn't as actively maintained as it probably should be. I started working on [mangathrV2](https://github.com/browningluke/mangathrV2) (a Go rewrite, but a WIP) which seeks to do everything this does, and more.

Regarding your issue, did you install it with `npm install -g mangathr` or build it from source?

If you built it from source, you might have forgotten to run `npm run build`.

**Comment by Drun555** [comment]
Firstly I tried to install it with regular way and catched this issue, and after it I tried to build - without success too, unfortunately. I have this issue on my Raspberry Pi 4 and M1 Mac, both working on aarch64 architecture. Perhaps, it could be a problem.

**Comment by browningluke** [comment]
It was an error on my end, the build CI/CD was releasing without building first for some reason. 

I've patched that and created a new release. Please try a `npm install -g mangathr` again, and let me know!

**Comment by Drun555** [comment]
Thank you for the fix :)
MODULE error is gone, but, unfortunately, now I'm receiving different issue. Maybe I should just wait for Go-rewrite version :)

```
/usr/local/lib/node_modules/mangathr/dist/plugins/mangaplus.js:43
            "Session-Token": crypto_1.default.randomUUID()
                                              ^

TypeError: crypto_1.default.randomUUID is not a function
    at new MangaPlus (/usr/local/lib/node_modules/mangathr/dist/plugins/mangaplus.js:43:47)
    at Object.<anonymous> (/usr/local/lib/node_modules/mangathr/dist/plugins/index.js:17:25)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/mangathr/dist/commands/manage.js:18:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```

**Comment by browningluke** [comment]
No worries! Indeed, I was having a few issues with Node.js so I jumped ship to Go. I'll make some doc commits tomorrow in that other repo to hopefully get you started with it :)

What command were you running that gave that error by the way? With a fresh install on my end, running `mangathr download mangaplus ...` works.

**Comment by browningluke** [comment]
It looks like the `crypto` package is very deprecated at this point. Not sure why it was still working for me. Just released a hotfix replacing it. 

A `npm update -g mangathr` should hopefully get you working without having to comment it out. 😄
